name: push to bitbucket
on: push
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
        ref: 'main'
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
         key: ${{ secrets.SSH_PRIVATE_KEY }}
         name: id_rsa # optional
         known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - run: |
        git remote add orgrepo git@github.com:5G00BD88-3006-Innovaatioprojekti/Test-repo.git
        git config --global user.email " tulonenvili@gmail.com"
        git config --global user.name "vtulonen"
        git checkout main
        git push -u orgrepo main
